package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os/signal"
	"syscall"
	"time"

	"islands/internal/auth"
	"islands/internal/game"
	"islands/internal/httpapi"
	"islands/internal/realtime"
	"islands/internal/storage"
)

func main() {
	addr := flag.String("addr", ":8080", "HTTP listen address")
	authSecret := flag.String("auth-secret", "dev-secret-change-me", "HMAC auth secret")
	visibleRadius := flag.Int("visible-chunk-radius", 2, "visible chunk radius: 1 for 3x3, 2 for 5x5")
	worldMap := flag.String("world-map", "", "path to world.islmap generated by cmd/mapbuilder")
	worldJournal := flag.String("world-journal", "", "path to world journal; defaults next to -world-map")
	worldPlayers := flag.String("world-players", "", "path to player state; defaults next to -world-map")
	compactWorld := flag.Bool("compact-world", false, "compact journal into world map and exit")
	compactWorldOnStart := flag.Bool("compact-world-on-start", false, "compact journal into world map before serving")
	compactWorldInterval := flag.Duration("compact-world-interval", 0, "compact journal into world map while serving; 0 disables periodic compaction")
	storageBatchInterval := flag.Duration("storage-batch-interval", time.Second, "batch dirty world writes for this duration; 0 writes synchronously")
	storageBatchMaxChunks := flag.Int("storage-batch-max-chunks", 128, "flush batched storage early after this many dirty chunks")
	flag.Parse()

	hub := realtime.NewHub()
	cfg := realtime.Config{VisibleChunkRadius: int32(*visibleRadius)}.Normalize()
	gameService := game.NewService(hub, cfg)
	if *worldMap != "" {
		ctx := context.Background()
		if *worldJournal == "" {
			*worldJournal = storage.DefaultJournalPath(*worldMap)
		}
		if *worldPlayers == "" {
			*worldPlayers = storage.DefaultPlayersPath(*worldMap)
		}
		fileStore := storage.NewFileStore(*worldMap, *worldJournal, *worldPlayers)
		loaded, err := fileStore.LoadWorld(ctx)
		if err != nil {
			log.Fatal(err)
		}
		if *compactWorld || *compactWorldOnStart {
			if err := fileStore.Compact(ctx, loaded.Chunks, loaded.Tick); err != nil {
				log.Fatal(err)
			}
			fmt.Printf("compacted world map %s and reset journal %s\n", *worldMap, *worldJournal)
		}
		if *compactWorld {
			return
		}
		var runtimeStore storage.Store = fileStore
		if *storageBatchInterval > 0 {
			runtimeStore = storage.NewBatchingStore(fileStore, storage.BatchConfig{
				FlushInterval:  *storageBatchInterval,
				MaxDirtyChunks: *storageBatchMaxChunks,
			})
			fmt.Printf("storage batching enabled: interval=%s, max dirty chunks=%d\n", *storageBatchInterval, *storageBatchMaxChunks)
		}
		gameService.SetStore(runtimeStore)
		if err := gameService.LoadWorld(1, loaded); err != nil {
			log.Fatal(err)
		}
		gameService.SeedDemoActor(1)
		fmt.Printf("loaded world map %s: %dx%d cells, %d chunks, journal=%s, players=%s, tick=%d\n", *worldMap, loaded.Width, loaded.Height, len(loaded.Chunks), *worldJournal, *worldPlayers, loaded.Tick)
	} else {
		gameService.SeedDemoWorld(1)
		fmt.Println("using in-memory demo world; pass -world-map artifacts/generated/world.islmap to load generated terrain")
	}
	server := httpapi.NewServer(auth.NewManager(*authSecret, 24*time.Hour), gameService, hub)

	httpServer := &http.Server{Addr: *addr, Handler: server}
	errs := make(chan error, 1)
	go func() {
		errs <- httpServer.ListenAndServe()
	}()

	stopCtx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()
	if *worldMap != "" && *compactWorldInterval > 0 {
		go runWorldCompactor(stopCtx, gameService, *compactWorldInterval)
		fmt.Printf("periodic world compaction enabled: interval=%s\n", *compactWorldInterval)
	}

	fmt.Printf("islands backend listening on %s, visible radius=%d\n", *addr, cfg.VisibleChunkRadius)
	select {
	case <-stopCtx.Done():
		fmt.Println("shutdown requested; saving player state and flushing storage...")
		storageCtx, cancelStorage := context.WithTimeout(context.Background(), 5*time.Second)
		if err := gameService.Shutdown(storageCtx); err != nil {
			log.Printf("storage shutdown failed: %v", err)
		} else {
			fmt.Println("storage saved")
		}
		cancelStorage()

		fmt.Println("closing realtime streams...")
		hub.Close()

		httpCtx, cancelHTTP := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancelHTTP()
		if err := httpServer.Shutdown(httpCtx); err != nil {
			log.Printf("graceful http shutdown timed out: %v", err)
			if closeErr := httpServer.Close(); closeErr != nil {
				log.Printf("forced http close failed: %v", closeErr)
			}
		} else {
			fmt.Println("http server stopped")
		}
	case err := <-errs:
		if err != nil && err != http.ErrServerClosed {
			log.Fatal(err)
		}
	}
}

func runWorldCompactor(ctx context.Context, gameService *game.Service, interval time.Duration) {
	if interval <= 0 {
		return
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			compactCtx, cancel := context.WithTimeout(ctx, interval)
			if err := gameService.CompactWorld(compactCtx, 1); err != nil {
				log.Printf("periodic world compaction failed: %v", err)
			} else {
				log.Printf("periodic world compaction completed")
			}
			cancel()
		}
	}
}
