package main

import (
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"time"

	"islands/internal/auth"
	"islands/internal/game"
	"islands/internal/httpapi"
	"islands/internal/mapgen"
	"islands/internal/realtime"
)

func main() {
	addr := flag.String("addr", ":8080", "HTTP listen address")
	authSecret := flag.String("auth-secret", "dev-secret-change-me", "HMAC auth secret")
	visibleRadius := flag.Int("visible-chunk-radius", 1, "visible chunk radius: 1 for 3x3, 2 for 5x5")
	worldMap := flag.String("world-map", "", "path to world.islmap generated by cmd/mapbuilder")
	flag.Parse()

	hub := realtime.NewHub()
	cfg := realtime.Config{VisibleChunkRadius: int32(*visibleRadius)}.Normalize()
	gameService := game.NewService(hub, cfg)
	if *worldMap != "" {
		loaded, err := loadWorldMap(*worldMap)
		if err != nil {
			log.Fatal(err)
		}
		if err := gameService.LoadChunks(1, loaded.Chunks); err != nil {
			log.Fatal(err)
		}
		gameService.SetWorldRenderSeed(1, loaded.Config.Seed)
		gameService.SeedDemoActor(1)
		fmt.Printf("loaded world map %s: %dx%d cells, %d chunks\n", *worldMap, loaded.Width, loaded.Height, len(loaded.Chunks))
	} else {
		gameService.SeedDemoWorld(1)
		fmt.Println("using in-memory demo world; pass -world-map artifacts/generated/world.islmap to load generated terrain")
	}
	server := httpapi.NewServer(auth.NewManager(*authSecret, 24*time.Hour), gameService, hub)

	fmt.Printf("islands backend listening on %s, visible radius=%d\n", *addr, cfg.VisibleChunkRadius)
	log.Fatal(http.ListenAndServe(*addr, server))
}

func loadWorldMap(path string) (*mapgen.Map, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	return mapgen.LoadBinary(file)
}
